#!/bin/bash
if [[ -z "$CFILE" ]]; then
	echo "Error: CFILE variable not set!"
	exit 1
fi

if [[ ! -f "$CFILE" ]]; then
	echo "Error: $CFILE is not valid!"
	exit 1
fi

gcc -S "$CFILE"

if [[ $? != 0 ]]; then
	echo "Error: code not successfull."
	exit 1
fi
